In [174]:
import pandas as pd
import numpy as np

In [175]:
df=pd.read_csv(r"C:\Users\bhetnarowicz\Desktop\projekt\cafe_sales.csv")

In [176]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [177]:
df.shape # Checking the number of rows and columns in the dataset

(10000, 8)

In [178]:
df.info() # Checking data types and the number of non-null values in each column

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [179]:
df.head() # Displaying the first five rows of the dataset

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [180]:
df.columns # Checking column names

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [181]:
df.isna().sum() # Checking for missing values

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [182]:
(df.isna().sum()/len(df)*100).round(2) # Checking the percentage of missing values in each column

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [184]:
df['Location']=df['Location'].str.strip().replace(['UNKNOWN', 'ERROR', 'NA'], 'Unknown').fillna('Unknown') # Removing leading and trailing whitespace and standardizing 'Unknown' values in the 'Location' column

In [185]:
df['Transaction Date']=pd.to_datetime(df['Transaction Date'], errors='coerce') # Converting 'Transaction Date' to datetime format, coercing errors to NaT for invalid dates

In [186]:
df['Transaction Date']=df['Transaction Date'].fillna(pd.Timestamp('1900-01-01')) # Filling missing 'Transaction Date' values with a placeholder date (January 1, 1900)

In [187]:
df['Payment Method'].value_counts(dropna=False) # Checking unique values and their frequencies in the 'Payment Method' column, including missing values

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [188]:
df['Payment Method']=df['Payment Method'].str.strip().replace(['UNKNOWN', 'ERROR', 'NA'], 'Unknown').fillna('Unknown') # Removing leading and trailing whitespace and standardizing 'Unknown' values in the 'Payment Method' column

In [189]:
df['Item'].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [190]:
df['Item']=df['Item'].str.strip().replace(['UNKNOWN', 'ERROR', 'NA'], 'Unknown').fillna('Unknown') # Removing leading and trailing whitespace and standardizing 'Unknown' values in the 'Item' column

In [191]:
df['Quantity'].value_counts(dropna=False) # Checking unique values and their frequencies in the 'Location' column, including missing values

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64

In [192]:
df['Quantity']=df['Quantity'].replace(['UNKNOWN', 'ERROR'], np.nan) # Replacing invalid entries in the 'Quantity' column with NaN

In [193]:
df['Price Per Unit'].value_counts(dropna=False)

Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
NaN         179
UNKNOWN     164
Name: count, dtype: int64

In [194]:
df['Price Per Unit']=df['Price Per Unit'].replace(['UNKNOWN', 'ERROR'], np.nan)

In [195]:
df['Total Spent'].value_counts(dropna=False)

Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
NaN        173
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [196]:
df['Total Spent']=df['Total Spent'].replace(['UNKNOWN', 'ERROR'], np.nan)

In [197]:
df['Transaction Date'].value_counts(dropna=False)

Transaction Date
1900-01-01    460
2023-02-06     40
2023-06-16     40
2023-03-13     39
2023-07-21     39
             ...
2023-09-24     15
2023-07-30     15
2023-03-11     14
2023-07-22     14
2023-02-17     14
Name: count, Length: 366, dtype: int64

In [198]:
df['Transaction Date'] = (df['Transaction Date'].replace(['UNKNOWN', 'ERROR'], np.nan))

In [199]:
df[df['Total Spent'].isna()] #Checking if there are any rows where 'Total Spent' is missing to see if they can be calculated from 'Quantity' and 'Price Per Unit'

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
25,TXN_7958992,Smoothie,3,4.0,NaN,Unknown,Unknown,2023-12-13
31,TXN_8927252,Unknown,2,1.0,NaN,Credit Card,Unknown,2023-11-06
42,TXN_6650263,Tea,2,1.5,NaN,Unknown,Takeaway,2023-01-10
65,TXN_4987129,Sandwich,3,NaN,NaN,Unknown,In-store,2023-10-20
...,...,...,...,...,...,...,...,...
9893,TXN_3809533,Juice,2,NaN,NaN,Digital Wallet,Takeaway,2023-02-02
9954,TXN_1191659,Coffee,4,2.0,NaN,Credit Card,In-store,2023-11-21
9977,TXN_5548914,Juice,2,3.0,NaN,Digital Wallet,In-store,2023-11-04
9988,TXN_9594133,Cake,5,3.0,NaN,Unknown,Unknown,1900-01-01
9993,TXN_4766549,Smoothie,2,4.0,NaN,Cash,Unknown,2023-10-20

In [200]:
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'], errors='coerce') # Converting 'Price Per Unit' to numeric type to enable calculations
df['Quantity']=pd.to_numeric(df['Quantity'], errors='coerce' ) # Converting 'Quantity' to numeric type to enable calculations
df['Total Spent']=pd.to_numeric(df['Total Spent'], errors='coerce') # Converting 'Total Spent' to numeric type to enable calculations

In [201]:
df[['Item','Price Per Unit']].value_counts(dropna=False) # Checking unique combinations of 'Item' and 'Price Per Unit' to identify potential inconsistencies in pricing for the same item

Item      Price Per Unit
Juice     3.0               1110
Coffee    2.0               1108
Cake      3.0               1085
Salad     5.0               1082
Sandwich  4.0               1082
Smoothie  4.0               1036
Cookie    1.0               1026
Tea       1.5               1023
Unknown   3.0                234
          4.0                213
          5.0                122
          2.0                119
          1.0                117
          1.5                110
Salad     NaN                 66
Tea       NaN                 66
Cookie    NaN                 66
Juice     NaN                 61
Smoothie  NaN                 60
Coffee    NaN                 57
Cake      NaN                 54
Unknown   NaN                 54
Sandwich  NaN                 49
Name: count, dtype: int64

In [202]:
df['Total Spent']=df['Total Spent'].fillna(df['Quantity']*df['Price Per Unit']) #Calculating 'Total Spent' for rows where it is missing using 'Quantity' and 'Price Per Unit'

In [203]:
df[(df['Total Spent'].notna())&(df['Quantity'].isna() | df['Price Per Unit'].isna())] # Checking if there are any rows where 'Total Spent' is present but 'Quantity' or 'Price Per Unit' is missing, which would indicate that 'Total Spent' cannot be calculated for those rows

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,NaN,1.0,2.0,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5.0,NaN,15.0,Unknown,Takeaway,2023-06-27
57,TXN_2080895,Cake,NaN,3.0,3.0,Digital Wallet,In-store,2023-04-19
66,TXN_8501819,Juice,NaN,3.0,6.0,Cash,Unknown,2023-03-30
...,...,...,...,...,...,...,...,...
9957,TXN_6487003,Coffee,NaN,2.0,8.0,Credit Card,Takeaway,2023-11-15
9961,TXN_2153100,Tea,2.0,NaN,3.0,Cash,Unknown,2023-12-29
9984,TXN_3142496,Smoothie,NaN,4.0,4.0,Cash,Takeaway,2023-07-27
9996,TXN_9659401,Unknown,3.0,NaN,3.0,Digital Wallet,Unknown,2023-06-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,Unknown,2023-12-02

In [204]:
df['Quantity']=df['Quantity'].fillna(df['Total Spent']/df['Price Per Unit']) # Calculating 'Quantity' for rows where it is missing using 'Total Spent' and 'Price Per Unit'

In [205]:
df['Price Per Unit']=df['Price Per Unit'].fillna(df['Total Spent']/df['Quantity']) # Calculating 'Price Per Unit' for rows where it is missing using 'Total Spent' and 'Quantity'

In [206]:
prices={'Coffee': 2.0,
        'Tea': 1.5,
        'Smoothie': 4.0,
        'Sandwich': 4.0,
        'Cookie': 1.0,
        'Salad': 5.0,
        'Cake': 3.0,
        'Juice': 3.0}    # Defining a dictionary with the most common price for each item based on the value counts
df['Price Per Unit']=df['Price Per Unit'].fillna(df['Item'].map(prices)) # Filling missing 'Price Per Unit' values based on the most common price for each item using the defined dictionary

In [207]:
df[['Item','Price Per Unit']].value_counts(dropna=False)

Item      Price Per Unit
Juice     3.0               1171
Coffee    2.0               1165
Salad     5.0               1148
Cake      3.0               1139
Sandwich  4.0               1131
Smoothie  4.0               1096
Cookie    1.0               1092
Tea       1.5               1089
Unknown   3.0                247
          4.0                227
          2.0                126
          5.0                124
          1.0                121
          1.5                118
          NaN                  6
Name: count, dtype: int64

In [208]:
item_map={2.0: 'Coffee',
          1.5: 'Tea',
          1.0: 'Cookie',
          5.0: 'Salad'}   # Defining a dictionary for products with unique prices

df.loc[df['Item']=="Unknown","Item"]=df.loc[df['Item']=="Unknown","Price Per Unit"].map(item_map) # Filling missing 'Item' values based on the unique price using the defined dictionary

In [209]:
df[['Item','Price Per Unit']].value_counts(dropna=False)

Item      Price Per Unit
Coffee    2.0               1291
Salad     5.0               1272
Cookie    1.0               1213
Tea       1.5               1207
Juice     3.0               1171
Cake      3.0               1139
Sandwich  4.0               1131
Smoothie  4.0               1096
NaN       3.0                247
          4.0                227
          NaN                  6
Name: count, dtype: int64

In [210]:
df['Quantity']=df['Quantity'].fillna(df['Total Spent']/df['Price Per Unit']) # Calculating 'Quantity' for rows where it is missing using 'Total Spent' and 'Price Per Unit'

In [211]:
df[df['Transaction ID'].duplicated(keep=False)] # Checking for duplicate 'Transaction ID' values to identify potential duplicate rows in the dataset

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [212]:
df[df['Item'].isna()] #Checking what left

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6,TXN_4433211,NaN,3.0,3.0,9.0,Unknown,Takeaway,2023-10-06
8,TXN_4717867,NaN,5.0,3.0,15.0,Unknown,Takeaway,2023-07-28
36,TXN_6855453,NaN,4.0,3.0,12.0,Unknown,In-store,2023-07-17
61,TXN_8051289,NaN,1.0,3.0,3.0,Unknown,In-store,2023-10-09
69,TXN_8471743,NaN,5.0,3.0,15.0,Digital Wallet,In-store,2023-04-06
...,...,...,...,...,...,...,...,...
9910,TXN_2338617,NaN,2.0,3.0,6.0,Digital Wallet,Unknown,2023-01-12
9918,TXN_2292088,NaN,1.0,4.0,4.0,Digital Wallet,Takeaway,2023-03-04
9946,TXN_8807600,NaN,1.0,4.0,4.0,Cash,Takeaway,2023-09-24
9981,TXN_4583012,NaN,5.0,4.0,20.0,Digital Wallet,Unknown,2023-02-27
9994,TXN_7851634,NaN,4.0,4.0,16.0,Unknown,Unknown,2023-01-08

In [213]:
df.loc[(df['Item'].isna()) & (df['Price Per Unit'] == 4.0), 'Item'] = 'Sandwich/Smothie'
df.loc[(df['Item'].isna())&(df['Price Per Unit']==3.0),'Item']='Juice/Cake'# Filling missing 'Item' values for rows where 'Price Per Unit' is 4.0 with 'Sandwich', which is the most common item with that price

In [214]:
df['Item'].value_counts(dropna=False) # Checking unique values and their frequencies in the 'Item' column after cleaning to ensure consistency

Item
Coffee              1291
Salad               1272
Cookie              1213
Tea                 1207
Juice               1171
Cake                1139
Sandwich            1131
Smoothie            1096
Juice/Cake           247
Sandwich/Smothie     227
NaN                    6
Name: count, dtype: int64

In [215]:
df=df.dropna(subset=['Item','Quantity','Total Spent']) # Dropping rows where 'Item' is still missing after attempts to fill it based on price, as these rows cannot be reliably imputed

In [220]:
df.info()

<class 'pandas.DataFrame'>
Index: 9957 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9957 non-null   str
 1   Item              9957 non-null   str
 2   Quantity          9957 non-null   int64
 3   Price Per Unit    9957 non-null   float64
 4   Total Spent       9957 non-null   float64
 5   Payment Method    9957 non-null   str
 6   Location          9957 non-null   str
 7   Transaction Date  9957 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 700.1 KB

In [222]:
df.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [217]:
df.to_csv(r"C:\Users\bhetnarowicz\Desktop\projekt\cafe_sales_cleaned.csv", index=False, decimal=',') # Saving the cleaned dataset to a new CSV file without the index column